version: '3'

env:
  D_COMPOSE: docker compose -f docker-compose.yaml
  DEV_COMPOSE: docker compose -f docker-compose.yaml -f dev-compose.yaml
  WEB_DOCKERFILE: Dockerfile
  API_V2_DOCKERFILE: api.v2.Dockerfile
  CONTAINERS: calcom-web calcom-api-v2 calcom-database calcom-redis

tasks:
  default:
    desc: Run the build task
    cmds:
      - $DEV_COMPOSE up -d calcom-database calcom-api-v2 # calcom-web

##########################################
################## TASKS #################
##########################################
  build:
    desc: Build all the services
    cmds:
      - DOCKER_BUILDKIT=0 $D_COMPOSE build --no-cache calcom-web calcom-api-v2
  up:
    desc: Start all the services
    cmds:
      - $D_COMPOSE up -d calcom-web calcom-api-v2
  start:
    desc: Start all the services in detached mode
    cmds:
      - $D_COMPOSE up -d calcom-web calcom-api-v2
  logs:
    desc: Show the logs of all the services
    cmds:
      - $D_COMPOSE logs -f --tail 300
  stop:
    desc: Stop all the services
    cmds:
      - $D_COMPOSE stop
  restart:
    cmds:
      - task: stop
      - task: start
  clean:
    desc: Stop and remove all the services
    cmds:
      - $D_COMPOSE down --volumes --remove-orphans --rmi local
  db-drop:
    desc: Clean the database
    cmds:
      - docker exec -e PGPASSWORD=${CALCOM_POSTGRES_PASSWORD} calcom-database psql -U ${CALCOM_POSTGRES_USER} -d ${CALCOM_POSTGRES_NAME} -c "TRUNCATE TABLE users CASCADE;"
  db-init:
    desc: Initialize the database
    cmds:
      - docker network create calcom || true
      - $D_COMPOSE up -d calcom-database calcom-redis
  full-init:
    desc: Init all
    cmds:
      - task: db-init # db is required - table creation are done in the next step
      - task: build
      - task: up
      - task: logs

##########################################
################### WEB ##################
##########################################
  web-build:
    desc: Build the web service
    cmds:
      - DOCKER_BUILDKIT=0 $D_COMPOSE build calcom-web
  web-up:
    desc: Start the web service
    cmds:
      - $D_COMPOSE up calcom-web
  web-start:
    desc: Start the web service in detached mode
    cmds:
      - $D_COMPOSE up -d calcom-web
  web-stop:
    desc: Stop the web service
    cmds:
      - $D_COMPOSE stop calcom-web

##########################################
############# CALCOM API V2 ##############
##########################################
  api-v2-build:
    desc: Build the calcom-api-v2 service
    cmds:
      - DOCKER_BUILDKIT=1 $D_COMPOSE build calcom-api-v2
  api-v2-up:
    desc: Start the calcom-api-v2 service
    cmds:
      - $D_COMPOSE up -d calcom-database calcom-redis calcom-api-v2
  api-v2-start:
    desc: Start the calcom-api-v2 service in detached mode
    cmds:
      - $D_COMPOSE up -d calcom-api-v2
  api-v2-stop:
    desc: Stop the calcom-api-v2 service
    cmds:
      - $D_COMPOSE stop calcom-api-v2
