version: '3'

env:
  D_COMPOSE: docker compose -f docker-compose.yaml
  WEB_DOCKERFILE: Dockerfile
  API_V2_DOCKERFILE: api.v2.Dockerfile
  CONTAINERS: calcom-web calcom-api-v2 calcom-database calcom-redis

tasks:
##########################################
################## TASKS #################
##########################################
  build:
      cmds:
      - DOCKER_BUILDKIT=0 $D_COMPOSE build --no-cache calcom-web calcom-api-v2
  up:
    cmds:
      - $D_COMPOSE up calcom-web calcom-api-v2
  start:
    cmds:
      - $D_COMPOSE up -d calcom-web calcom-api-v2
  stop:
    cmds:
      - $D_COMPOSE stop calcom-web calcom-api-v2

  clean:
    cmds:
      - docker stop $CONTAINERS || true
      - docker rm -f $CONTAINERS  || true
      - docker image rm calcom.docker.scarf.sh/calcom/cal.com calcom-api-v2 || true
      - docker volume prune -f || true

  init-db:
    cmds:
      - docker network create calcom || true
      - $D_COMPOSE up -d calcom-database calcom-redis

##########################################
################### WEB ##################
##########################################

  web-build:
    cmds:
      - DOCKER_BUILDKIT=0 $D_COMPOSE build calcom-web
  web-up:
    cmds:
      - $D_COMPOSE up calcom-web
  web-start:
    cmds:
      - $D_COMPOSE up -d calcom-web
  web-stop:
    cmds:
      - $D_COMPOSE stop calcom-web

##########################################
############# CALCOM API V2 ##############
##########################################

  api-v2-build:
      cmds:
      - DOCKER_BUILDKIT=1 $D_COMPOSE build calcom-api-v2
  api-v2-up:
      cmds:
      - $D_COMPOSE up calcom-api-v2
  api-v2-start:
      cmds:
      - $D_COMPOSE up -d calcom-api-v2
  api-v2-stop:
      cmds:
      - $D_COMPOSE stop calcom-api-v2
